#ifndef __SEMO_DIRECTION_HEADER__
#define __SEMO_DIRECTION_HEADER__
typedef enum SEMO_MOVE {
    SEMO_MOVE_FORWARD,
    SEMO_MOVE_LEFT,
    SEMO_MOVE_BACKWARD,
    SEMO_MOVE_RIGHT,
    SEMO_MOVE_STOP
} SEMO_MOVE;
#endif
